1. Create a Numpy array of size 4 x 5.

In [14]:
import numpy as np
x = np.array([[0,1,2,3,4],[4,5,6,7,8],[0,1,2,3,4],[4,5,6,7,8]])
print(x)

[[0 1 2 3 4]
 [4 5 6 7 8]
 [0 1 2 3 4]
 [4 5 6 7 8]]


2. Randomly initialize the array.

In [7]:
y=np.random.rand(3,2)
print(y)

[[0.84405081 0.05837376]
 [0.12194268 0.69571888]
 [0.72050237 0.80126291]]


3. Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [22]:
x = np.array([[1,1,10,3,14],[4,15,6,7,8],[8,1,2,3,4],[2,5,6,7,8],[4,9,6,7,8]])
# only square matrix allowed
dett = np.linalg.det(x)
print(int(dett))

# transpose of matrix
z = x.transpose()
print(z)

863
[[ 1  4  8  2  4]
 [ 1 15  1  5  9]
 [10  6  2  6  6]
 [ 3  7  3  7  7]
 [14  8  4  8  8]]


4. Create another matrix of size 5 x 4 and randomly initialize it.

In [2]:
import numpy as np
mat4 = np.random.rand(5,4)
print("Array initialized with Random value :\n",mat4)

Array initialized with Random value :
 [[0.72916849 0.91402765 0.7435103  0.7286343 ]
 [0.98162536 0.66169129 0.11650891 0.9828324 ]
 [0.36881613 0.44801243 0.39615633 0.84938638]
 [0.34206971 0.56952341 0.95948167 0.88530499]
 [0.21648354 0.52619391 0.23921044 0.43735275]]


5. Perform Matrix multiplication.

In [4]:
p = np.array([[0,1,2,3,4],[4,3,6,9,8],[4,5,3,3,4],[4,7,9,7,8]])
q = np.array([[2,9,6,3],[3,2,10,8],[2,1,6,9],[7,9,6,9],[10,3,5,2]])
print(np.dot(p,q))
print('\n')
# @ method
print(p@q)

[[ 68  43  60  61]
 [172 153 184 187]
 [ 90  88 130 114]
 [176 146 230 228]]


[[ 68  43  60  61]
 [172 153 184 187]
 [ 90  88 130 114]
 [176 146 230 228]]


6. Perform element wise matrix multiplication.

In [5]:
p = np.array([[0,1,2,3,4],[4,3,6,9,8],[4,5,3,3,4],[4,7,9,7,8]])
q = np.array([[2,9,6,3,6],[3,2,10,8,8],[2,1,6,9,2],[7,9,6,9,7]])
print(np.multiply(p,q))

[[ 0  9 12  9 24]
 [12  6 60 72 64]
 [ 8  5 18 27  8]
 [28 63 54 63 56]]


7. Find mean, median of the numpy array created.

In [29]:
w = np.array([7,1,2,3,9,7])
# median of 1D array
print(np.median(w))

# mean of 1D arary
print(np.mean(w))

5.0
4.833333333333333


8. Obtain each row in the second column of the first array.

In [19]:
print(p[0:,1])

[1 3 5 7]


9. Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv('Iris.csv')
print(data - np.mean(data,axis=0))

       Id  PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm Species
0   -74.5      -2.358667     -0.998667      -0.743333         0.446     NaN
1   -73.5      -2.358667     -0.998667      -0.943333        -0.054     NaN
2   -72.5      -2.458667     -0.998667      -1.143333         0.146     NaN
3   -71.5      -2.258667     -0.998667      -1.243333         0.046     NaN
4   -70.5      -2.358667     -0.998667      -0.843333         0.546     NaN
..    ...            ...           ...            ...           ...     ...
145  70.5       1.441333      1.101333       0.856667        -0.054     NaN
146  71.5       1.241333      0.701333       0.456667        -0.554     NaN
147  72.5       1.441333      0.801333       0.656667        -0.054     NaN
148  73.5       1.641333      1.101333       0.356667         0.346     NaN
149  74.5       1.341333      0.601333       0.056667        -0.054     NaN

[150 rows x 6 columns]


10. Study about numpy array attributes and implement it on the first matrix.

In [22]:
import numpy as np
a = np.array([[7,1,2,3,9],[5,3,7,3,2]]) 
print(a.shape)
b = a.reshape(5,2)
print(b)

(2, 5)
[[7 1]
 [2 3]
 [9 5]
 [3 7]
 [3 2]]
